### ISSUE TITLE
Mid Game Scoring with Panda-GLGO

### ISSUE THREAD

**Issue by PowerUser1234** [garywill/glGo#1]
I have a few questions about Panda-glGo and 64 bit Windows 10.

-There is no 64 bit Windows version of  Panda-glGo.  Is there going to be one?
  There is no Windows 1.4.1 binary version of Panda-glGo.  Is that going to happen?

-I tend to stick with Chinese Area scoring, and the GNUGO engine.  There 
doesn't seem to be any reliable mid-game way to get an accurate scoring of the 
board as though it were at the end of the game, there or not.  The scoring 
estimates that are available are so far off as to be useless.  Is this an area 
which can be changed?  Could mid-game Chinese Area scoring be implemented? 
Could a board highlighting system be implemented for Chinese Area scoring, illustrating
what stones and territory are included, and by default what stones are deemed dead
and not included?

**Comment by garywill** [comment]
Hi there
I just save a copy of the code here. 
I am not crews. Sorry
